### PR TITLE
support chain logo

### PR DESCRIPTION
**Pull request by hackmod**
## Description
It shows the chain logo to prevent somebody from sending their coins to the wrong address.

currently added chain logos (svg images)
- ETH, ETC, ETH Testnets(default), EXP, UBQ, POA, ELLA, ETSC, CLO, MUSIC, ESN, EGEM, AKROMA, TOMO, GO,EOSC

## screenshot

image

image

image

image (update with the new etc logo)

image

image

image

## on mobile
image

### CODE REVIEW

**Comment by ghost** [comment]
Please add EOSC logo also :smile:

**Comment by hackmod** [comment]
where can I find any official SVG chain logo?

**Comment by mkrufky** [comment]
Very nice!

**Review by gamalielhere — APPROVED** [review]
Gonna wait for @eosclassicteam to get included on this change

**Comment by hackmod** [comment]
rebased. @gamalielhere EOSC already included 😄 
image

**Pull request merged**
