### PR TITLE
Update ethTokens.json

### PR DESCRIPTION
**Pull request by Lukalala**

### CODE REVIEW

**Comment by 409H** [comment]
Hi, please can you give your social/website links and support email in the PR also.

**Comment by Lukalala** [comment]
We have not started ICO, official website currently is not convenient
announced

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
不含病毒。www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by tayvano** [comment]
We will pull this in when there is a customer support email address. Until then, users can add manually if they need to: https://myetherwallet.groovehq.com/knowledge_base/topics/how-to-see-a-new-token-in-myetherwallet

**Comment by Lukalala** [comment]
thank you for reply. it's useful.

**Pull request closed without merging**
