### PR TITLE
Added WhoHas contract ABI

### PR DESCRIPTION
**Pull request by Lebski**
The WHO Token is an extended ERC20 Token. It connects the social platform WhoHas to the ethereum blockchain.
Website will be public in a few hours.

### CODE REVIEW

**Comment by kvhnuke** [comment]
hi can you post a public link to your website/platform

**Comment by Lebski** [comment]
Sure!
whohas.io

**Comment by Lebski** [comment]
Conflicts solved

**Comment by SteveMieskoski** [comment]
Moved to MyEtherWallet/Ethereum-lists [PR #495](https://github.com/MyEtherWallet/ethereum-lists/pull/495)

**Comment by SteveMieskoski** [comment]
Hey, @Lebski  I found three functions present in this ABI that are not present in the ABI available via etherscan.  They are 'circulatingSupply_', 'maxSupply_', 'balances'.

**Comment by SteveMieskoski** [comment]
Hey, @Lebski I found three functions present in this ABI that are not present in the ABI available via etherscan. They are 'circulatingSupply_', 'maxSupply_', 'balances'.

**Comment by SteveMieskoski** [comment]
Hey, @Lebski I found three functions present in this ABI that are not present in the ABI available via etherscan. They are 'circulatingSupply_', 'maxSupply_', 'balances'. Are they supposed to be present? Thanks

**Comment by Lebski** [comment]
Hi!
@SteveMieskoski, thank you for checking. 
We updated the contract and the ABIs got merged. 
But it's should be fine.

**Comment by gamalielhere** [comment]
moved #1673

**Pull request closed without merging**
