### PR TITLE
devop/remove-x888

### PR DESCRIPTION
**Pull request by gamalielhere**
- Remove x888 for inactivity

### CODE REVIEW

**Comment by fxsecltd** [comment]
Please, remove this merge since x888.io still operates and valid. during one month it was under attack. 
screen

**Comment by gamalielhere** [comment]
@fxsecltd Do you have the link to the blockchain explorer you guys use?

**Comment by fxsecltd** [comment]
Currently we can explore it via MEW only - custom node adding (url: https://eightereum.x888.io:443 eip-155=true, chainid 888 for read only operations and chainid=0 for state changing operations). You can check it anytime, it working ok.

**Comment by kvhnuke** [comment]
@fxsecltd is it possible for you to have your own blockchain explorer?

**Comment by fxsecltd** [comment]
Yes, we have planned this in next year. If our node causes some troubles, larger then other custom nodes, added in custom node list - please, let me know.

**Pull request merged**
