### PR TITLE
Support for translating Geth error messages

### PR DESCRIPTION
**Pull request by ugilio**
- Added support for translating Geth error messages via double lookup
- ATM, only transaction-related messages (from go-ethereum/core/tx_pool.go) are provided, but it might be enough.
- Added Italian translations for those messages

### CODE REVIEW

**Comment by ugilio** [comment]
I played around with this and it turned out to be quite simple.

Basically, if in the future someone notices an untranslated message coming from geth, it is enough to do this:
- Add that message to globalFuncs.gethErrors (as 'Message' : 'key')
- Add that message again to en.js (as key: 'Message')
- Update the other language files

**Comment by tayvano** [comment]
I'm going to have @kvhnuke check this one and pull it in. I wonder if there is like a big list of geth messages somewhere? Maybe I'll ask in the gitter channel tomorrow.

**Comment by ugilio** [comment]
I extracted a list from geth but it was something like 350 messages, but I think only a small subset could actually reach MEW via RPC.

**Comment by tayvano** [comment]
Ha. Okay good call on not grabbing all the messages 😄

I think I got all of them on all languages now. Seems to be working at least. I have a staging site @ http://supergeniustay.com/myetherwallet/ if you want ot look

**Pull request merged**
