### PR TITLE
Add dcn token

### PR DESCRIPTION
**Pull request by wparad**

### CODE REVIEW

**Comment by wparad** [comment]
Hmmm, maybe the symbol should be `٨`, instead of `DCN`  Alphabetically, where does that go?  Next to `L`?

**Comment by sebastiaanhol** [comment]
This is the coin information 
"address":"0x08d32b0da63e2C3bcF8019c9c5d849d7a9d791e6",
"symbol":"DCN",
"decimal":0,
"type":"default"

**Comment by tayvano** [comment]
already added

**Comment by sebastiaanhol** [comment]
Top

Op ma 15 jan. 2018 om 10:54 schreef Taylor Monahan <notifications@github.com

**Pull request closed without merging**
