### PR TITLE
Generate a docker image

### PR DESCRIPTION
**Pull request by acroca**

### CODE REVIEW

**Comment by kvhnuke** [comment]
Hi this is cool :) will you also be able to add a self signed cert to  nginx so that it can be server over ssl?

**Comment by acroca** [comment]
I think self signed certs are not valid for most browsers, right?

**Comment by kvhnuke** [comment]
Yea but you can easily add an exception, this will enable users to use hardware wallets as well

**Comment by kvhnuke** [comment]
https://github.com/benjaminion/eth-parity-qnap/wiki/Connecting-to-MyEtherWallet

**Comment by acroca** [comment]
Added it. Ideally if this has to go to production it'll need a better nginx conf and good ssl certificates, which can be mounted into the container to replace the given ones.

**Comment by kvhnuke** [comment]
Wow that was fast! I'll test it soon! I agree but this will work as well, since it generates a new certificate when the container starts. User just need to add an exception once

**Pull request merged**
