### PR TITLE
Added EagleCoin contract ABI

### PR DESCRIPTION
**Pull request by eaglexblockchain**
Dear Mew Support,

We are from EagleCoin (EAGLE) team www.eaglepay.io, we need your support in order to get listed in Mew.
For your information we have been listed in CoinMarketCap: https://coinmarketcap.com/currencies/eaglecoin/

Below are EagleCoin details:

Name of cryptocurrency : EagleCoin
Ticker Symbol : EAGLE
Type : ERC20
Logo : https://drive.google.com/file/d/0B-O68OiszGDfUjZfSW1aOFU2Wjg/view
Website : https://eaglepay.io/
Our second email is: team@eaglepay.io (same as the website which refer to team@eaglecoinindonesia.com)
Bitcointalk Thread : https://bitcointalk.org/index.php?topic=2384214
Reddit: https://www.reddit.com/user/EagleCoin_EAGLE/
CoinMarketCap link : https://coinmarketcap.com/currencies/eaglecoin/
Video Presentation: https://www.youtube.com/watch?v=0c-by2uPR4c&t=68s

Please provide a URL that shows the total supply of coins in real time : https://etherscan.io/token/0x994f0dffdbae0bbf09b652d6f11a493fd33f42b9

How many coins are held by the creators, developers, or are reserved for other purposes? Provide block explorer links and addresses if available.
● Developer : 1,500,000 EAGLE
● Marketing and Others : 1.500,000 EAGLE
● Bounties and Air Drop : 600,000 EAGLE

Block explorer: https://etherscan.io/token/0x994f0dffdbae0bbf09b652d6f11a493fd33f42b9
https://ethplorer.io/address/0x994f0dffdbae0bbf09b652d6f11a493fd33f42b9

Twitter Account : https://twitter.com/EaglecoinID

Chat Page : https://t.me/eaglecoinworld

Source code repository : https://github.com/elangindonesia/EagleCoin

Any other information:
EagleCoin is the first step of the EaglePay project, which is aimed at developing a
payment gateway system using blockchain technology. EagleCoin is an ERC20 Ethereum token
that functions as a digital asset. EagleCoin holders will receive a 1:1 EagleShare upon the ICO
(Initial Coin Offering). Each EagleShare represents one ownership unit of EaglePay Holding;
EagleShare holders will receive an annual dividend (if any) from the net profit of EaglePay
Holding. The dividend will be given as an EAGLE (unit of EagleCoin) and/or ether.
EagleCoin investors will receive three benefits. First, they are eligible to receive a
staking reward. Second, as EagleShare holders, they will receive an EagleShare token and
dividend (dependent upon the performance of EaglePay Holding). Finally, investors will
receive a profit if the value of EagleCoin increases. We believe, with our roadmap and limited
number of tokens in supply, the value of EagleCoin will increase significantly. However, it is
important to note that we are not able to define the target price at this time because it depends
on the market mechanism.

Thank you for your help and support.

Regards,

EagleCoin Team

### CODE REVIEW

**Comment by eaglexblockchain** [comment]
Hi, seems the build is error, could you help us?

**Comment by tayvano** [comment]
Can you link me directly to your ABI, or paste it here @elangindonesia

**Comment by eaglexblockchain** [comment]
Hi Taylor,


Thank you so much for replying, EtherScan link :
https://etherscan.io/address/0x994f0dffdbae0bbf09b652d6f11a493fd33f42b9#code


Regards,


Mateus Yonathan

**Comment by tayvano** [comment]
I just added it manually. should be live at some point tongiht

**Pull request closed without merging**
