### PR TITLE
GBP Support

### PR DESCRIPTION
**Pull request by paxpelus**
Please check this PR and close previous one (https://github.com/kvhnuke/etherwallet/pull/502)

### CODE REVIEW

**Comment by crptm** [comment]
LGTM (not tested)

**Comment by kvhnuke** [comment]
@tayvano what do you think about using cryptocompare api instead of bity to get the prices? this will allow us to merge this request as GBP is not supported by bity api

**Comment by tayvano** [comment]
@kvhnuke You have to talk to @crptm about the different APIs. We have cryptocompare and ethplorer.io and someone else, all who have reached out to me regarding their API. I passed along to him. 

I have no opinion on what we use as I really don't use this feature so whatever users want / easy to implement.

**Comment by kvhnuke** [comment]
@crptm your thoughts? I really have no idea about cryptocompare limitations

**Comment by tayvano** [comment]
Okay heres the message from ethplorer:

We added current prices to token's API. So you can easy show token and transactions prices in USD using same API as before. Just structure added: price: { # token price (false, if token is non-tradeble) rate: # current rate currency: # token price currency (USD) diff: # 24 hour rate difference (in percent) ts: # last rate update timestamp },
There's a sample address balance with a lot of tokens: https://ethplorer.io/address/0xd47297cdcf36eed17305d6a5471c6cd482c7e91c

Price history will be available soon.

Enjoy :slightly_smiling_face:

---

And cryptocompare:

hola, thanks again for an awesome product most of our team uses and generally recommends myetherwallet. I think I've mentioned it before but if you want more than just ETH and REP prices you can use our min api: https://t.co/k5e6OSYCOR  You can add any combination of token and currencies.

**Comment by crptm** [comment]
@kvhnuke i'd say deploy it and if they are not ready for traffic - too bad :) This shouldn't break anything on our side.

**Pull request merged**
