### PR TITLE
Added SHIT Token to Defaults

### PR DESCRIPTION
**Pull request by shitoshi**
https://www.shitcoin.io/

shitoshi@shitcoin.io

### CODE REVIEW

**Comment by tayvano** [comment]
[Your shit looks a bit centralized, yo.](https://ethplorer.io/address/0xef2e9966eb61bb494e5375d5df8d67b7db8a780d#tab=tab-holders) When's your ICO? 😂

**Comment by shitoshi** [comment]
Hi there @tayvano 💩

The ISD (Initial Shit Distribution) just happened! I used an innovative method in which people earned SHIT by posting about it on social media and coding the distributions in the constructor of the contract https://etherscan.io/address/0xef2e9966eb61bb494e5375d5df8d67b7db8a780d#code so while there are few transactions, the SHIT has been spread far and wide!

Also HUGE fan of MEW!!! I would like to send you some 💩 for all your amazing work advancing our beloved Ethereum community. Please let me know your MEW address 💩💩💩

Look forward to seeing SHIT listed in MEW. Please help spread it far and wide from your friends, to charities, your loved ones, meaningful projects, and hedge funds of course!

**Comment by tayvano** [comment]
Alright fucker, you better send some to the donation address. 😂

**Comment by tayvano** [comment]
You get in mostly because you did 100x as much work as legit tokens. 🥇

**Comment by shitoshi** [comment]
Woohoo!!! I have sent you a large pile of 💩💩💩💩💩 Please spread 💩 far and wide 😂😂😂

Let's get this listed and go to Uranus!! We can be #1 on CoinMarketCap soon. Welcome to the rocket ship!

Please join our growing community of Shitheads on Slack https://shitcoin-slack-invite.herokuapp.com

https://etherscan.io/tx/0x2727a8c51c2dae5c90ab582c7de66a855a4b2893514b0b839c197ca0d2c2d057

**Pull request merged**
