### PR TITLE
Integration for EtherFact

### PR DESCRIPTION
**Pull request by etherfact**
Many user wishing they can store the coins from our network on there trezor and have native support from you guys from the official site.

EIP155 enabled chain ID is 1.

https://www.etherfact.org is our website.

Many thanks to MyEtherWallet

### CODE REVIEW

**Comment by BadAimWeeb** [comment]
bump

**Comment by gamalielhere** [comment]
@etherfact Can you fix the conflicts?

**Comment by etherfact** [comment]
@gamalielhere Yes the conflicts I have fixed on commit will work for EtherFact network.

**Comment by gamalielhere** [comment]
@etherfact I meant the github conflicts so we can merge your branch.

**Comment by etherfact** [comment]
@gamalielhere 
There was no conflict at all

**Comment by etherfact** [comment]
wallet.etherfact.org
We are still using and no error occurred

**Comment by kvhnuke** [comment]
Can you please confirm the chainid, it is empty and chainid 1 is main ETH, if you are using chainid 1 as well, then we cannot add this network since it'll enable replay attacks

**Comment by etherfact** [comment]
i'm using ChainID 1

**Comment by etherfact** [comment]
source: https://github.com/EtherFact-Project/go-etherfact/blob/master/params/config.go
ChainId:             big.NewInt(1)

**Comment by gamalielhere** [comment]
Closing this. Reason:  
> if you are using chainid 1 as well, then we cannot add this network since it'll enable replay attacks

**Pull request closed without merging**
