### PR TITLE
Rewriting the polish translation

### PR DESCRIPTION
**Pull request by egzumer**
You overwritten my translation with another not completed one.

### CODE REVIEW

**Comment by tayvano** [comment]
Weird. I'm still seeing these translations on my local branch? Sorry about that 😞

Do you want me to merge now or are you still working on it?

**Comment by egzumer** [comment]
There was some other participant that made the pull request, he didn't notice my translation. His was barely started and You merged it after mine. Not a problem, just wanted to make it clear.

The basic part is finished, there is just the help that need to be translated. I'll try to finish it but i guess It won't be today.

**Comment by tayvano** [comment]
Sorry about that. I'm going to try to do the Pull Requests not at 2am from now on. Thank you so much for all your hard work on this. We really appreciate it.

**Comment by egzumer** [comment]
Actually I checked it again and it looks like it was my mistake :), I closed my first pool request before You merged it because I thought it was already merged. This was my first pull request on github and I misunderstood how it exactly works. Sorry about the fuss, I guess I learned something new today :).
Cheers!

**Pull request merged**
