### PR TITLE
Added STX token and token sale

### PR DESCRIPTION
**Pull request by lbeder**
Website: https://www.stox.com (please note, that due to regulatory compliance, the site is blocked in US and in Israel).
Github: https://github.com/stx-technologies/stox-token
Twitter: https://t.me/joinchat/DByWw0Pnq9BAy4FqPv_Lyg
Reddit: https://www.reddit.com/r/STOX/
Twitter: https://twitter.com/stx_coin
Token Offering Start Time: 1501682400 (August 2, 2017 2:00:00 PM, seconds)

### CODE REVIEW

**Comment by lbeder** [comment]
Very weird that there is a conflict :O. I see a different `app/scripts/customGas.js` in my repo and I've made sure that I'm fully synced.

**Comment by tayvano** [comment]
I think something is half-merged. I may need to manually do this. I'll make sure its in for tonights release though

**Comment by lbeder** [comment]
Yeah, it was a very weird conflict for me - I couldn't get the latest `mercury` for some reason...

**Comment by lbeder** [comment]
🙏

**Comment by tayvano** [comment]
manually added 2 days agp bc weird merge stuff.

**Pull request closed without merging**
