### PR TITLE
Added EXMR Token to Defaults

### PR DESCRIPTION
**Pull request by exmrcoin**
Website: https://exmr.io
Telegram: https://t.me/joinEXMR/
Reddit: https://www.reddit.com/u/eXMRcoin
Discord https://discord.gg/eNhFzgy

### CODE REVIEW

**Comment by Aldrinx00** [comment]
Fix it asap thanks

**Comment by deppil90** [comment]
Pull Request #1021 deppil90/0x8b442c5B6907C69078c442ac25B64818E683aF0b

**Comment by BLOCKER123** [comment]
great coin my address 0xC58D3876a94DdF168A9D5E470dE3C34d79B5Af09

**Comment by deppil90** [comment]
no

2017-11-12 4:47 GMT+07:00 BLOCKER123 <notifications@github.com>:

**Comment by Ghen27** [comment]
Pull Request #1255
Ghen27

**Comment by Nusy** [comment]
0x65378cE4385C490A8827Fcfd14dD732990D788e2

**Comment by mkmathur08** [comment]
Pull Request #1255
mkmathur

**Comment by Ronjet08** [comment]
Whats This??

**Comment by jasfe08** [comment]
Pull request #1255
Jasfe08

**Comment by BLOCKER123** [comment]
Pull request #1255
BLOCKER123

**Comment by freshbread1** [comment]
Pull request #1255

**Comment by Mazzarothleo** [comment]
Pull request #1255

**Comment by souinfo** [comment]
Pull request #1255

**Comment by genius-Loci** [comment]
Pull request #1255

**Comment by pinkyb** [comment]
Pull requests #1255
pinkyb

**Comment by zarkasi92** [comment]
Pull requests #1255

**Comment by tsoyens** [comment]
EXMR 

0x1BC9DC64976C29Ca094f856f58b3d9904e7052D7

**Comment by tsoyens** [comment]
PULL REQUEST #1255

**Comment by pedangrusak** [comment]
Pull request #1255

**Comment by yitzjoe** [comment]
Pull request #1255

**Comment by Joenstronger** [comment]
Pull request #1255

**Comment by Mazzarothleo** [comment]
Pull request #1255

**Comment by Wheeng** [comment]
Pull tequest #1255

**Comment by Mazzarothleo** [comment]
Pull Request #1255

**Comment by dianepot** [comment]
Pull Request

**Comment by dianepot** [comment]
Pull Request #1255

**Comment by Remedy88** [comment]
Pull Request #1255

**Comment by Remedy88** [comment]
Pull Request #1255                                                                                                                                                          
Remedy88  0x6389CfC0F5eFBb14117415256dfb4D161E1e4c54

**Pull request merged**
