### PR TITLE
Added Ink Protocol contract ABI

### PR DESCRIPTION
**Pull request by geehwan**
add the Ink Protocol contract for users to create and respond to Ink Protocol transactions within p2p marketplaces, including starting a new transaction, accepting an existing transaction, creating a dispute, solving a dispute, and leaving feedback for a completed transaction.

### CODE REVIEW

**Comment by gamalielhere** [comment]
@geehwan Just wanted to verify, there seems to be functions on this ABI that doesn't show up in etherscan. '__address0__', '__address2__', '__address2__', '__address3__'. Are they supposed to be present?

**Comment by gamalielhere** [comment]
moved [#520](https://github.com/MyEtherWallet/ethereum-lists/pull/520)

**Comment by geehwan** [comment]
Hi! Oh true, I can actually remove those from the ABI.. want me to create a new pull request?

**Comment by gamalielhere** [comment]
@geehwan just update this one and I'll verify it.

**Comment by gamalielhere** [comment]
@geehwan I'm closing this now. Refer to #1673 for the change.

**Pull request closed without merging**
