### PR TITLE
Add Secalot hardware wallet support

### PR DESCRIPTION
**Pull request by Secalot**

### CODE REVIEW

**Comment by kvhnuke** [comment]
i received the wallets today!! yey! cant wait to test them

**Comment by gamalielhere** [comment]
@Secalot Running this atm. Seems that pressing the connect button results in an error.  
`Error in event handler for (unknown): TypeError: str.match is not a function`

**Comment by Secalot** [comment]
@gamalielhere

Hi gamalielhere,

The "Error in event handler for (unknown): TypeError: str.match is not a function" would appear if Chrome for some reason can't successfully communicate with a U2F device (secalot in this case).

Out of my head, this can be the reason:
1. Running the website over http and not over https. Chrome does not allow U2F when using http at all.
2. In my pull request there are four commits. The first one introduced most of the changes, and the second one changed some things in the U2F message format secalot is using. If for some reason the first commit was applied from the PR, but the next three were not, the error you are seeing will appear. The first line of the SecalotUsb.prototype.exchange function should look like "var apdu = new Buffer('1122334455667788' + apduHex, 'hex');" after successfully applying the PR.

If the above two reasons do not apply, can you please do a quick check and place a breakpoint at line 92 of secalotEth.js (error callback in SecalotEth.prototype.getAddress) and check the errorCode field of the error object. The errorCode will give an indication of why things are not working. Decoding of the error code is available at https://gist.github.com/KenanSulayman/68f26c6e95d195bc3b89#file-u2f-js-L43 u2f.ErrorCodes object.

Just to be on the safe side, I've checked out a fresh copy of https://github.com/kvhnuke/etherwallet.git and applied my pull request https://patch-diff.githubusercontent.com/raw/kvhnuke/etherwallet/pull/1648.patch After resolving a merge conflict in signMsgCtrl.js and building it with "npm install + npm run dist" things did work for me locally.

**Comment by gamalielhere** [comment]
@Secalot I apologize. It was actually because my local env wasn't setup with ssl. I tested it and it works fine. If you can fix the conflicts, we can possibly merge this on the next release.

**Comment by Secalot** [comment]
@gamalielhere Is there any action pending on me to be done for this PR?

**Pull request merged**
