### PR TITLE
Adding Synapse (SYN) token

### PR DESCRIPTION
**Pull request by wQwRtaufxJw7UFLCXzXz**
Adding Synapse (SYN) Token for https://synapse.ai/ for SYN Contract at https://etherscan.io/address/0x10b123fddde003243199aad03522065dc05827a0

Building a Decentralized Data + Machine Learning marketplace and network. Initial coin offering starts in 4 days and we're going to start distributing our pre-sale tokens.

Site: https://synapse.ai/
Pre-sale: https://presale.synapse.ai/
About us: https://presale.synapse.ai/about
Bitcoin Talk ANN: https://bitcointalk.org/index.php?topic=2198553
Twitter: https://twitter.com/aisynapse
Founder: https://twitter.com/dpg
Support: support@synapse.ai

### CODE REVIEW

**Comment by dpgailey** [comment]
Building a Decentralized Data + Machine Learning marketplace and network. Initial coin offering starts in 4 days and we're going to start distributing our pre-sale tokens. 

Pre-sale: https://presale.synapse.ai/
About us: https://presale.synapse.ai/about 
Bitcoin Talk ANN: https://bitcointalk.org/index.php?topic=2198553
Twitter: https://twitter.com/aisynapse

**Comment by wQwRtaufxJw7UFLCXzXz** [comment]
Hi @tayvano @kvhnuke Can you please help and get this merged for our users? Our launch happens tomorrow and it would be awesome to have this working. We're also listed on ED: https://etherdelta.com/#SYN-ETH

Thanks for the epic product, support, and help. :)

**Comment by tayvano** [comment]
Need a support email address before I pull this in @dpgailey

**Comment by dpgailey** [comment]
@tayvano support@synapse.ai Thanks!

**Comment by wQwRtaufxJw7UFLCXzXz** [comment]
@tayvano updated the original text. 👍

**Comment by wQwRtaufxJw7UFLCXzXz** [comment]
@tayvano also contributed for all your badass work. srsly. 
 https://etherscan.io/tx/0xaf25ab8ff1ff5cc6a215b585961228cc7bb6336080f3ffa542891f28cafd7341

**Pull request merged**
