### PR TITLE
Added Render Token contract

### PR DESCRIPTION
**Pull request by arodic**
Website: https://rendertoken.com/
Rocket Chat: https://rendertoken.rocket.chat/ 
Reddit: https://www.reddit.com/r/RenderToken/
Twitter: https://twitter.com/rendertoken
Support email: info@rendertoken.com

### CODE REVIEW

**Comment by tayvano** [comment]
Please add your support email. Thank you

**Comment by tayvano** [comment]
Please include support email. Instructions here: https://myetherwallet.github.io/knowledge-base/tokens/token-creators-add-your-token-to-myetherwallet.html

**Comment by arodic** [comment]
Maybe @AugustoL can help with this? I'm not part of RenderToken dev team.

**Comment by AugustoL** [comment]
Me neither, I will send an email to the ones who hired me for the development with this thread

**Comment by kalinstoy** [comment]
Hi all, RNDR team here. What do I have to do to submit our support email? It is info@rendertoken.com - I couldn't find a clear portal to do so in the link.

**Comment by arodic** [comment]
I updated the pull request description with relevant information.

**Pull request merged**
