### PR TITLE
Update de.js

### PR DESCRIPTION
**Pull request by HuhnSolo**
Mostly corrected grammar and Spelling. One general question for me is - what is more appropriate, using the formal you (Sie) or the unformal (Du)? I would prefer Du.

### CODE REVIEW

**Comment by tayvano** [comment]
@Neugierdsnase & @Mawalu - any thoughts? 

I would lean towards informal as well as most of the English is generally very laid back and informal. However that is based on my personality, and I obviously don't really know what, if any, the cultural implications would be in another language. 

What do you most commonly see around the web?

**Comment by HuhnSolo** [comment]
I think the informal variant represents more the (as I understand you) community idea of the project. Or as I see the project too. So it's not so much about "laid back" to me, it's more about is the side/the project speaking to friends or to costumers.

**Comment by mawalu** [comment]
Well I use the English interface on most websites so I don't know whats common there. To be honest I just continued with formal since it was the one already used.

But if I think about it the informal one makes more sense in this project.

**Comment by Neugierdsnase** [comment]
I personally agree with "Du" as being more contemporary, I chose the formal version for sake of consistency since the one(s) before me chose it. Fun fact though, the English "you" linguistically derives from the German "Sie", not "du".

**Comment by HuhnSolo** [comment]
Fine, I could start to convert it to "Du" this evening.

**Comment by tayvano** [comment]
I'm going to merge this in now but looking forward to watch it evolve! Thank you so much!

**Pull request merged**
