### PR TITLE
Add ethereum social network

### PR DESCRIPTION
**Pull request by ghost**
Ethereum Social (aka ETSC) is a community-oriented POW ethereum network.

+ EIP-155 enabled and Chain id 214.
+ Tested on https://wallet.ethereumsocial.kr
+ Trezor support tested in the ellawallet fork
+ More info on gazua.tv (kor) (eng will be supported soon)

### CODE REVIEW

**Comment by hackmod** [comment]
This is a hardfork of the original EtherSocial Coin.

The origianl Site is http://ethersocial.org (in Korean), https://ethersocial.org/eng/index.html (English)

and this is https://ethereumsocial.kr regraded as a **SCAM** site of the original EtherSocial.

**Comment by ghost** [comment]
@hackmod Funny, We don't have any ideas on your plan or your thinking however, I believe that you have a wrong opinion, unless you can prove that we are a fishy scam.

By the way, http://ethereumsocial.kr is a temp site for now, and we use http instead.

**Comment by ghost** [comment]
@hackmod For now there is "no" supporting node or a single services for the "ethersocial" scam.
Instead, me and the real ethereum social community decided to fork a dead, useless chain, to a stable, and reliable network, @hackmod If you can prove that our node or network is a scam, you can just make a PR for the so called "ethersocial" node.  I think you have a short thought,

**Comment by eastcoinuser** [comment]
@hackmod 22 contributions vs 190 contributions
I think we have a winner here 😄

**Comment by ghost** [comment]
@hackmod He is a **fake** account based on **DDENGLE.com** 's site. Also "ddengle.com" is a scam site which is running by **a scam exchange** https://www.coindesk.com/south-korean-bitcoin-exchange-declare-bankruptcy-hack/

**Comment by ghost** [comment]
@hackmod 거기까지만 해도 되는걸 사기라고 펌훼하시면 저희도 가만 안 있습니다. 하시는거 뭐든지 간에 저희가 당한거랑 똑같이 해드릴게요 😄 해킹당한 거래소가 하는 프로젝트가 뭐가 좋아서 졸졸 따라다니는지 모르겠지만요 자존심도 없으시나 ㅋㅋㅋㅋㅋ

**Comment by ghost** [comment]
Sorry for making a messy conversation here however we have a scammer who tries to manipulate the consensus.

**Comment by ghost** [comment]
https://github.com/MyEtherWallet/ethereum-lists/pull/451

**Comment by hackmod** [comment]
hmm...

@eastcoinuser // I have a strong evidence about @akx20000a 's bad behavior,
but he is young man. he has good ability. So I do not want to argue with him to make these things worse.

guess what?
This Korean young man's recent behavior...
almost all cryptocurrency traders in Korea already know about him...

**Comment by ghost** [comment]
@hackmod LOL you are beating around the bush aren't you?
You can say anything however you have the responsibility too.

And yeah almost every cryptocurrency trader knows youbit and their fishy scam either.

**Comment by ghost** [comment]
@hackmod 거기까지만 해도 되는걸 사기라고 펌훼하시면 저희도 가만 안 있습니다. 하시는거 뭐든지 간에 저희가 당한거랑 똑같이 해드릴게요 😄 해킹당한 거래소가 하는 프로젝트가 뭐가 좋아서 졸졸 따라다니는지 모르겠지만요 자존심도 없으시나 ㅋㅋㅋㅋㅋ

**Comment by ghost** [comment]
@hackmod @ddengle @쌍둥아빠 Please answer my question, who is the owner of "Youbit " and "Ethersocial"? https://github.com/ethersocial/go-esc/issues/14

**Comment by kvhnuke** [comment]
wow, whats going on here? please provide me with multiple other sources to verify the legitimacy of this network

**Comment by ghost** [comment]
@kvhnuke This is a duplicate pr with https://github.com/EthereumCommonwealth/etherwallet/pull/27 and we will soon provide a new node with a new loadbalancer and some other materials like whitepapers and the homepage.

**Comment by hackmod** [comment]
Ethereum Social Project != EtherSocial Project and the Ethereum Social is mere a hardfork of the real EtherSocial Coin.

EtherSocial Coin (ESC) | Ethereum Social Coin (ETSC)
------------------------|----------
https://ethersocial.org/eng/index.html | no homepage (http://ethereumsocial.kr/ )
White paper (in Korean now) : https://ethersocial.org/eng/index.html#whitepaper | no white paper
Community support (Since 2013~ most Popular blockchain/mining community in Korea) : https://www.ddengle.com | FIXME
Devs : @ethersocialcoin , @KIM-MYEONGHUN  | @akx20000a , @bitminings (owner of https://http://www.gazua.tv )
Source code release date (Jan 31, 2018) : https://github.com/ethersocial/go-esc (See also the attached image)  | a fork of the original ESC after their release date. (Feb 9, 2018)
Network Hash rate : ~100GH/s | ~1.5GH/s
not official pool sites : about ~5. https://en.escpool.com , https://esc.gonsmine.com/ https://esc.dreampool.info | only 1 (https://mineesc.com . not mine **"etsc"** dot com ) hardforked at this site.
network state (peer explorer) : https://escstats.gonsmine.com | https://stats.ethereumsocial.kr/
Feed back site : https://www.ddengle.com/esc_board | http://www.gazua.tv/post/ho

image

cross post at EthereumCommonwealth#27

See also BTCPrivate/BitcoinPrivate/issues/37 and @hsol 's comment

**Comment by ghost** [comment]
@hackmod Get lost, you are not a Ethereum Social developer nor "EtherSocial" developer
And I am not a related person of you call it "Bitcoin Platinum" or whatever 😄

**Comment by ghost** [comment]
# SCAM WARNING: EtherSocial Network(ESN) is a ethereum based fork coin made by a HACKED cryptoexchange
## Youbit exchange bankruptcy

https://www.cnbc.com/2017/12/19/yapian-youbit-exchange-files-bankruptcy.html
https://news.bitcoin.com/korean-exchange-youbit-bankruptcy-members-options/
http://www.econonews.co.kr/news/articleView.html?idxno=15503
http://www.sporbiz.co.kr/news/articleView.html?idxno=183524

## Relationship between ddengle.com and youbit

http://biz.chosun.com/site/data/html_dir/2017/12/19/2017121902494.html
https://www.ddengle.com/board_free/4446196
https://www.ddengle.com/board_free/3651725
http://gall.dcinside.com/board/view/?id=bitcoins&no=4461654

## Conclusion

+ Youbit has been started as a "ddengle" exchange
+ They hacked twice, and there was no apology or refunds (Instead, they gave victims their company's stock)
+ They assumed that they are in "bankruptcy" mode, and now they are making a huge "ponzi" scam coin called ESC
+ They premined about 50% ESC of a total supply, now it is in danger of being hacked again.

## My opinion

I think ESC is the expansion package of "yam" scam Fin.

**Comment by ghost** [comment]
@hackmod Get lost, this is an open source community, and not a trading forum, though :)

**Comment by hackmod** [comment]
@akx20000a ETSC is a hardfork at 150,000 block height of the ESC blockchain. that's the most important fact.

dude. Please came down and relax. your future is bright and promising, except this childish behavior.

**Comment by ghost** [comment]
@hackmod Whatever you say, Ethereum Social(ETSC) is a dedicated chain with a different monetary policy with EtherSocial(ESC) and stop advertising your coin at Ethereum Social(ETSC) issue!

**Comment by ghost** [comment]
Ok, here is the deal

## Comparison between Ethereum Social(ETSC) and EtherSocial(ESC)

Ethereum Social Coin (ETSC) | EtherSocial Coin (ESC)
-- | --
Running by http://gazua.tv and some several community sites | Running by a scam exchange https://youbit.co.kr )
No hacked or scam experience | Several hacked experience and the trial is in progress
Official services running | No official services or support
Devs : @akx20000a(experienced engineer in blockchain) @bitminings(Operator of bitmining service) | Hired man from youbit.co.kr(also known as a scammer & doesn't have any security knowledge
Global user support(including this pr) | No global support (cause ESC is a localized scam)

Also they have no experience with git system (see https://github.com/ethersocial/go-esc/commits/develop for their terrible work) + They don't have any open-source mind. ( They removed all of the copyright information https://github.com/ethersocial/go-esc/blob/develop/COPYING)

**Comment by hackmod** [comment]
See also ethersocial/go-esc/issues/4 Ive already posted about it - Copyright notices and commit history
and they already know this issue.

This is my temporal work on this issue. https://github.com/hackmod/go-ethereum/commit/51261e6e34184068466f584669e725997893ebe9 already mentioned as a comment (not a pull request. this fixed repo has all commit history of the go-ethereum repo.)

So many Korean devs are not familiar with OpenSource and opensource minded. but this situation are so common.

- https://github.com/etherzero-org/go-etherzero (Chinese dev.) - EtherZero project removed almost all commit history of go-ethereum repo.
- Even Bytecoin author deleted his own commit history - https://github.com/bcndev/bytecoin - from https://github.com/amjuarez/bytecoin
- syfares/Barandos/issues/1 - Barandos cryptocurrency project Copyright notice issue.
- https://github.com/bitcoincandyofficial/bitcoincandy (Chinese dev) - Bitcoin Candy project removed all commit history of the original Bitcoin-ABC

**Comment by ghost** [comment]
Closing this for now

**Pull request closed without merging**
