### PR TITLE
small clean up

### PR DESCRIPTION
**Pull request by Zwilla**
Note on clean up automatic on line 29 return will be deleted.
Now the code is minifying safe ! Missing some {} and ;

### CODE REVIEW

**Comment by dternyak** [comment]
Hey @Zwilla :)

Thanks for all of your PRs.

I have some security concerns around the large diffs here.

Is it possible for you to submit small diffs with only the exact improvement you've made?

Also, do you mind explaining what it is exactly you are fixing a bit more clearly?

Thanks.

**Comment by Zwilla** [comment]
ohh, it looks only on GitHub so crazy. With a normal text editor it looks very simple what I have changed.
I added only some missing brackets on line 25 and line 27 / 28 and 30
on line 24 will later add a secure new Buffer.from function, after you merge this one.

Compare it by your self with BB-Edit or NotePad and you will see all is fine.

**Comment by dternyak** [comment]
@Zwilla 

It isn't GitHub -- that patch that you have submitted contains large amounts of changes (even if they are all very minor).

Perhaps you can start checking how large the changes you are making is before submitting? 

Thanks.

**Comment by Zwilla** [comment]
Here it comes!
[https://github.com/kvhnuke/etherwallet/pull/883/commits/b4a6eafec3c9d16daf8952922a8e02fec5eeefa5?w=1](https://github.com/kvhnuke/etherwallet/pull/883/commits/b4a6eafec3c9d16daf8952922a8e02fec5eeefa5?w=1)

Hope we all learned about this trick: https://github.com/camsong/chrome-github-mate/issues/5
EDIT:
〜〜Here I have imported the files!
http://www.mergely.com/JOzKO6be/

Click there on OPTIONS -> ignore white space :)〜〜

**Pull request closed without merging**
