### PR TITLE
support 32bits chainId with the latest Ledger app

### PR DESCRIPTION
**Pull request by hackmod**
Please see https://github.com/LedgerHQ/blue-app-eth/commit/8260268b0214810872dabd154b476f5bb859aac0
for some larger chainId cases, returned signature v should be recomputed at the client side.

Currently, Ledger returns only `1-byte` truncated signature `v`. but it contains `signature v bit`. so we can recalculate for given chainId by `v = chainId * 2 + 35 + signature v bit`.

### CODE REVIEW

**Comment by mkrufky** [comment]
Thank you for this, @hackmod .  Akroma Ledger support depends on this changeset.  I'll make note of it in the Akroma PR #1976

**Comment by kvhnuke** [comment]
@gre can you please verify these changes? also are these breaking changes? for example will Ledger with older firmware versions will continue work and is it available with latest ledger firmware

**Comment by gre** [comment]
This lgtm. It also shouldn't break anything.

**Review by gamalielhere — APPROVED** [review]

**Comment by hackmod** [comment]
https://github.com/EthereumCommonwealth/etherwallet/pull/202
https://github.com/MyCryptoHQ/MyCrypto/pull/2094

**Pull request merged**
