### PR TITLE
Add POA network

### PR DESCRIPTION
**Pull request by rstormsf**
Regarding: https://github.com/kvhnuke/etherwallet/issues/1425

Questions:
Warning for HD paths for Ledger. Please advice on how to fix them.
How to set default gasPrice to 1 gwei?
Anything else I should know/add before submitting PR?

Deployed version: https://wallet.poa.network

After PR gets merged, we will destroy our MEW deployed version

### CODE REVIEW

**Comment by tayvano** [comment]
Are you guys compliant with EIP-155?

**Comment by tayvano** [comment]
(That is where the chainid comes from. It prevents replays.)

**Comment by rstormsf** [comment]
Yes, we are! @tayvano 

To prove:

```
{
  "blockHash": "0x98cdeabaa7534262817d49bee8012f8a144436e5f9498c5972c365462bdff116",
  "blockNumber": "0x101ea",
  "chainId": "0x63",
  "condition": null,
  "creates": null,
  "from": "0x0039f22efb07a647557c7c5d17854cfd6d489ef3",
  "gas": "0x7b0c",
  "gasPrice": "0x3b9aca00",
  "hash": "0x4a1f64983974c1ce98e0cf325804fd98beefeae72473bcfcd2965f57a83f5d7b",
  "input": "0x",
  "nonce": "0xc",
  "publicKey": "0xca9043062adb891af6ce3101b3002bc0d50092f4374de2044b5f78bed838cb6f8b353aaf780e1062657ae8f3e36345a4b1294c78be511ceabcd9341020823d82",
  "r": "0x86abc71712fba165c5d0409b466cf6eddc7bb32bad3d1bc85fd935d41502b836",
  "raw": "0xf86c0c843b9aca00827b0c940039f22efb07a647557c7c5d17854cfd6d489ef388016345785d8a00008081eaa086abc71712fba165c5d0409b466cf6eddc7bb32bad3d1bc85fd935d41502b836a039e2cb555f5579176887d5c0627b1c23353279d0586792c4fab71ba0a8fc5b41",
  "s": "0x39e2cb555f5579176887d5c0627b1c23353279d0586792c4fab71ba0a8fc5b41",
  "standardV": "0x1",
  "to": "0x0039f22efb07a647557c7c5d17854cfd6d489ef3",
  "transactionIndex": "0x0",
  "v": "0xea",
  "value": "0x16345785d8a0000"
}
```
this is the tx that was generated at ChainId=99, or `0x63` in hex.

Feel free to submit this same `raw` to chainId = 1, and you will get an error of Invalid Network Id.

Here is proof submitting the transaction above that was already initiated at POA network to Ethereum Mainnet:

screen shot 2017-12-19 at 12 54 15 pm

URL link where the same tx was submitted in POA:
https://core-explorer.poa.network/tx/0x5cfd16cf3b7df1dcebf05b8d0345ae609de84af6db52080b1afe217158d24ff1

**Comment by rstormsf** [comment]
@tayvano does that fullfil your request?
🙏

**Comment by tayvano** [comment]
Sorry @rstormsf, I got this thread mixed up with the other one. Yes all looks good. I can have this live TMR with new token loading thingies. Undergoing final tests.

**Comment by rstormsf** [comment]
YEAH!! thank you so much! @tayvano

**Pull request merged**
