### PR TITLE
Add Back to Earth ETH tokens (GT & SRC)

### PR DESCRIPTION
**Pull request by sammy007**
This patch adds SRC and GT tokens.

### CODE REVIEW

**Comment by tayvano** [comment]
Thank you @sammy007! Perfectly executed & **thank you** for even alphabetizing! 👏 😃 👏

**Comment by sammy007** [comment]
Dear @tayvano, it seems BTE screwed distribution and they need to re-issue token also, I will make cumulative PR later.

**Comment by tayvano** [comment]
@sammy007 Sounds like fun. At least people are getting good at reissuing tokens? 😒

**Comment by sammy007** [comment]
Please revert, these tokens are no longer makes sense. We expect new one this year (hopefully).

**Comment by tayvano** [comment]
@sammy007 so you want me to remove GT and SRC for now?

**Comment by sammy007** [comment]
Yep :( there will be new tokens reissued soon (tm), these 2 does not make sense.

**Comment by sammy007** [comment]
They reissued. This is why I asked to revert.

SRC -> STRC `0x46492473755e8dF960F8034877F61732D718CE96` 8 decimals
GT -> GTKT `0x025abad9e518516fdaafbdcdb9701b37fb7ef0fa` 0 decimals

**Pull request merged**
