### PR TITLE
temporal fix to workaround EIP155 issue with chainid > 255

### PR DESCRIPTION
**Pull request by hackmod**
See also https://github.com/LedgerHQ/ledgerjs/issues/168

### CODE REVIEW

**Comment by hackmod** [comment]
802fbfc89733c27 commit does not work with web3 at all

**Comment by gamalielhere** [comment]
We can't allow this, this pretty much opens up replay attack, since it is no longer using EIP155

**Comment by hackmod** [comment]
@gamalielhere // thank you for your reply.

ClassicalEtherWallet already use similar method for their CLO ledger support.
https://github.com/EthereumCommonwealth/etherwallet/pull/136/commits/f1e6423f2857e23b7db68002c959b8792a4a7204#diff-6e71ea384f1daaf034cc00196569e772R216

anyway, I've separated previous PR into two commit.
- ef32de746ad use EIP155 settings for customRPC case. in this case, user can use `EIP155 disabled` at his own risk. (but this logic is not needed. since `eip155 == false` cases `rawTx.chainId == 0`)
- 49d5674 temporally disable EIP155 support for `chainId < 256` case (similar method for CLO with ClassicalEtherWallet)

**Comment by ghost** [comment]
@hackmod ClassicEtherWallet decided to support Callisto Ledger patch for enabling their Callisto deposit. It is very dangerous for using the patch widely

**Comment by hackmod** [comment]
finally, the latest ledger support EIP155 + 32bits chainid.

**Pull request closed without merging**
