### PR TITLE
add ICN (Iconomi) to default tokens

### PR DESCRIPTION
**Pull request by ghost**
Proof: https://medium.com/iconominet/iconomi-icn-apptoken-genesis-under-way-d18324d95365#.8n53qu9d2

### CODE REVIEW

**Comment by ghost** [comment]
@tayvano you've added not correct ICN values. It has 18 decimals, while you added only 3. Many Iconomi users are now confused with the huge balance in mew. Please see this pull request.

**Comment by tayvano** [comment]
Shoot. Sorry. Too much stuff going on obviously! Thank you!

**Comment by ghost** [comment]
Thanks, @tayvano, but please delete the wrong ICN token with the 3 decimals, because now you have two ICN tokens:
https://github.com/kvhnuke/etherwallet/blob/mercury/app/scripts/tokens.js

**Comment by tayvano** [comment]
LOL. I got it! Just pushed it live. Does that look correct now?

**Pull request merged**
