### PR TITLE
X3.10.x offline signing dp

### PR DESCRIPTION
**Pull request by realcodywburns**

### CODE REVIEW

**Comment by tayvano** [comment]
Ahhhhhhhh 👼🌈

Ready for testing?

Also, I noticed you had a loading thing or something? Can you give me a json or js array thing where I can turn the loading thing to have short messages - like slack does?

**Comment by GriffGreen** [comment]
I love this!

**Comment by realcodywburns** [comment]
I thought of how to do it better as soon as i walked out the door. Ignore last commit

**Comment by tayvano** [comment]
I'm going to merge it so I can continue cleanup without having to deal with a messy merge later

**Pull request merged**
