### PR TITLE
Added Primalbase Token (PBT) contract ABI

### PR DESCRIPTION
**Pull request by shoreward**

### CODE REVIEW

**Comment by gamalielhere** [comment]
@shoreward For verification purposes, can you show the contract source code?

**Comment by gamalielhere** [comment]
Also it's moved [#519](https://github.com/MyEtherWallet/ethereum-lists/pull/519)

**Comment by shoreward** [comment]
@gamalielhere please specify where to send the contract code to you

**Comment by gamalielhere** [comment]
@shoreward you can email it at support@myetherwallet.com

**Comment by gamalielhere** [comment]
@shoreward Closing this PR now. It's moved here [#519](https://github.com/MyEtherWallet/ethereum-lists/pull/519)

**Comment by shoreward** [comment]
Hey. We sent the contract code for a verification from admin@primalbase.com to support@myetherwallet.com

**Comment by gamalielhere** [comment]
@shoreward yes. Its been merged. The token will be there on the next release.

**Comment by shoreward** [comment]
Oh, thanks! We really looking forward for the next release :)

**Pull request closed without merging**
