### PR TITLE
small code clean up

### PR DESCRIPTION
**Pull request by Zwilla**
small code clean up and notes on todo

### CODE REVIEW

**Comment by dternyak** [comment]
Hey @Zwilla :)

Thanks for all of your PRs.

I have some security concerns around the large diffs here.

Is it possible for you to submit small diffs with only the exact improvement you've made?

Also, do you mind explaining what it is exactly you are fixing a bit more clearly?

Thanks.

**Comment by Zwilla** [comment]
https://github.com/kvhnuke/etherwallet/pull/882/commits/1753d94ee9e076dd1be73a90095bd95c83c510ba?w=1

Just add ?w=1 :)

**Comment by tayvano** [comment]
I'm not merging anything this big. You tell us to be more secure but expect me to merge a 300 line diff with a description of "small code clean up".

I'm about to simply lock v3 for good as the issues stemming from pull requests and merges are causing more headaches than they are worth. 

We would love you to contribute, but you must understand that we cannot trust you or this PR due to the fact it appears every single line has changed.

**Comment by Zwilla** [comment]
ok, for the future I will add the ?w=1 tag behind the merge url, than you can see how small it was. 
[https://github.com/kvhnuke/etherwallet/pull/882/commits/1753d94ee9e076dd1be73a90095bd95c83c510ba?w=1](https://github.com/kvhnuke/etherwallet/pull/882/commits/1753d94ee9e076dd1be73a90095bd95c83c510ba?w=1)

**Pull request closed without merging**
