### PR TITLE
Added DPP token to defaults

### PR DESCRIPTION
**Pull request by ercchy**
https://support.cofound.it/hc/en-us/articles/115001315351-Crowdsale-token-list-information
https://cofound.it/en/projects/digital-assets-power-play/

### CODE REVIEW

**Comment by tayvano** [comment]
Thanks @ercchy 

Can you give me a brief rundown on the relationship between cofound.it and the tokens as well as what the support process looks like in regards to that. 

I can't stay up to date on all that is going on, and we have had no issues so far, I'm mostly just curious for moving forward. :)

**Comment by ercchy** [comment]
Sure,
all the pull request sent by me are the startups, which Cofound.it is running crowdsales for. Meaning, we are guiding them through the whole process of turning their ideas into a token model and preparing the whole team for the crowdsale and all the things that follow the crowdsale as well. We are also providing them with the smart contracts for the crowdsale and the token and I am the one deploying them, thus all the pull requests come from me.

We have a support ticketing system https://support.cofound.it/hc/en-us where users can open any issue they have during the crowdsale. We are aware that good support is of up-most importance, especially during the crowdsale. Thus we have a few people specially dedicated, and deals only with answering and helping out users and also catching any complaints on any social media. Basically, we are working really hard to make a crowdsale process as pleasant and as transparent as possible for everyone that want to support the great startups that we handpick.

**Comment by tayvano** [comment]
Pretty cool. Like I said, we haven't noticed any big issues with the tokens you've added so obviously you are doing something right. Keep it up and have fun!

**Comment by JohnnySheffield** [comment]
Hi! Nikola from DA PowerPlay here - the owner of the DPP token contract. I'm just dropping by to say hi and express my thanks to guys from cofound.it and mew for a great work. I'm here if anything is needed.

**Pull request merged**
