### PR TITLE
use customNode implementation with epool node for etc

### PR DESCRIPTION
**Pull request by hyugit**
Hi there,

I'm not sure if using **customNode** is your preferred way of implementing a node, but it is certainly a very powerful feature as it can help you easily scale to numerous node providers effortlessly.

In this tentative PR, I used a **customNode** to add the etc node from @etherninja

Please check **nodeHelpers/mewEtc.js** and **nodes.js** file for details.

there are merge conflicts for **etherwallet-master.js** files, so this pull request could be used only as a reference point.

Thank you again,

trave7er

### CODE REVIEW

**Comment by kvhnuke** [comment]
Does ETC support EIP155 now?

**Comment by hyugit** [comment]
yes it does: https://github.com/ethereumproject/go-ethereum/releases/tag/v3.2.3

**Comment by splix** [comment]
@trave7er, @kvhnuke ETC chain_id for EIP155 is `61`

**Comment by hyugit** [comment]
hi everyone,

I'll withdraw this PR in light of the additional changes we need to make. I'll cooridnate with @etherninja and present one PR for the changes regarding the ETC blockchain.

Thanks,

Huang

**Comment by ghost** [comment]
It looks like I was volunteered :-) I will put something together after the fork.

**Comment by tayvano** [comment]
Lol. @etherninja you guys focus on the fork and once that happens we can help out switching over. I think round 1 will be switching etc to eip155 =true and the chainid. Round 2 will be replacing our server info with yours. :)

**Comment by ghost** [comment]
It looks like eip155 already set. :-) still plan to use the node?

**Comment by tayvano** [comment]
Yeah we just have to test it and stuff. You got ssl set up, right?

**Comment by hyugit** [comment]
@tayvano yes, ssl is setup. please refer to *scripts/nodeHelpers/mewEtc.js* for details. thanks

**Pull request closed without merging**
