### PR TITLE
Updated "Ethorse Rewards" contract address

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Review by gamalielhere — COMMENTED** [review]
@ethorse is there any documentation or announcement for this?

**Comment by ghost** [comment]
@gamalielhere We updated them in our instruction docs.
Docs: https://github.com/ethorse/ethorse-rewards
Commit diff: https://github.com/ethorse/ethorse-rewards/commit/d89d7ed3ae212430799276a85e63842a9453369d

**Comment by gamalielhere** [comment]
@ethorse Awesome! Thanks!

**Review by gamalielhere — APPROVED** [review]

**Comment by ghost** [comment]
How long does it take to update in the website?

**Pull request merged**
