### PR TITLE
Add Lottereum (LTE)

### PR DESCRIPTION
**Pull request by demartini**
This patch add Lottereum (LTE) Token & Contract ABIs.

### CODE REVIEW

**Comment by tayvano** [comment]
@demartini Can you please provide support address and any other links to Lottereum (forums, website, whatever is best place to find info or get help)

**Comment by demartini** [comment]
Hello @tayvano for now the best place is the official ANN (https://bitcointalk.org/index.php?topic=2038170).

**Comment by tayvano** [comment]
We will not add a custom token without a direct customer support line.

**Comment by demartini** [comment]
I'll get in touch with them, and then I'll get back to you.

Thanks for the attention.

**Pull request closed without merging**
