### PR TITLE
Add GBP to Equivalent Values list #440

### PR DESCRIPTION
**Pull request by paxpelus**

### CODE REVIEW

**Comment by crptm** [comment]
Can you please remove build artefacts from the commit? I am also interested if these values are used on swap screen or not.

**Comment by paxpelus** [comment]
hmmm, when I run gulp clean both the files in dist & chrome-extension folders did not get removed. I thought that was normal. Are these 2 the files you need me to remove?

**Comment by paxpelus** [comment]
About swap page, only ETH, BTC, REP values are used there. Maybe someone can clarify if the values I changed affect that page? I tested locally and I see correct values in swap page.

**Comment by crptm** [comment]
> Are these 2 the files you need me to remove?

Yep.

> Maybe someone can clarify if the values I changed affect that page?

Looks like it uses different values so we should be ok.

**Pull request closed without merging**
