### PR TITLE
added token CAT(BitClave)

### PR DESCRIPTION
**Pull request by markshw**
website:  https://www.bitclave.com

### CODE REVIEW

**Comment by tayvano** [comment]
@markshw Please include a support email. Thank you.

**Comment by markshw** [comment]
support email: help@bitclave.com

**Comment by tayvano** [comment]
So FYI, I already have a token with the symbol CAT. I will just put a note on each of them, but I recommend you look into this.

{
"symbol"      : "CAT",
"address"     : "0x56ba2Ee7890461f463F7be02aAC3099f6d5811A8",
"decimals"    : "18",
"name"        : "Blockcat",
"ens_address" : "",
"website"     : "https://blockcat.io",
"logo": {
  "src"       : "",
  "width"     : "",
  "height"    : "",
  "ipfs_hash" : ""
},
"support": {
  "email"     : "team@blockcat.io",
  "url"       : ""
},
"social": {
  "blog"      : "",
  "chat"      : "",
  "facebook"  : "",
  "fourm"     : "",
  "github"    : "",
  "gitter"    : "",
  "instagram" : "",
  "linkedin"  : "",
  "reddit"    : "",
  "slack"     : "https://slack.blockcat.io",
  "telegram"  : "",
  "twitter"   : "https://twitter.com/blockcatio",
  "youtube"   : ""
}
},

**Comment by markshw** [comment]
Hi @tayvano , when can I see the token in MEW token list
thanks
Mark

**Pull request merged**
