### PR TITLE
HelloGold retired GBT and launched GOLDX

### PR DESCRIPTION
**Pull request by DaveAppleton**
HelloGold has retired the old GBT contract and launched the new GOLDX as a stable coin for those times when crypto volatility has you knackered.

### CODE REVIEW

**Comment by GENERALGUBERNATOR1** [comment]
ТЫ ЗАКОЛЕБАЛ

**Comment by DaveAppleton** [comment]
link to announcement
https://medium.com/hellogold/hgt-has-been-unfrozen-and-can-be-freely-traded-fbc97608b30a

**Comment by DaveAppleton** [comment]
Is it something I said / did that upset your CI system ? 😢

**Comment by wparad** [comment]
It was something that was fixed in #1526 literally merged after this one.

**Pull request merged**
