### PR TITLE
Add COB Token

### PR DESCRIPTION
**Pull request by aitjcize**
Added Cobinhood Token.

Contract Address: 0xb2f7eb1f2c37645be61d73953035360e768d81e6

Email: support@cobinhood.com
Website: https://cobinhood.com
Twitter: https://twitter.com/cobinhood
Slack: http://slack.cobinhood.com/
Telegram: https://t.me/cobinhood
Github: https://github.com/cobinhood
Medium: https://medium.com/@cobinhood

### CODE REVIEW

**Comment by tayvano** [comment]
@aitjcize Need support email.

**Comment by aitjcize** [comment]
what do you mean?

**Comment by tayvano** [comment]
Please read  https://myetherwallet.groovehq.com/knowledge_base/topics/i-just-created-a-new-token-can-you-add-it-to-mew in full

**Comment by aitjcize** [comment]
Updated. Thanks.

**Pull request merged**
