### PR TITLE
bugfix/tx-generation

### PR DESCRIPTION
**Pull request by gamalielhere**
- Fixes the display issue when generating a tx
Related: #2133

### CODE REVIEW

**Comment by un1t** [comment]
I cloned bugfix/tx-generation branch and executed "npm i && npm run dist"
Number of zeros seems to be correct. But I notice couple more things

1. When unit is wei, all works fine, but when unit is gwei after refreshing page and generating information value of gas price was 7.1.  In gas price range input there is other value, in my case it was 9. Have no idea why gas price 7.1 no matter what value is in gas price range input.

2. When I tried connect to Ledger, it did not work, and there was error in console:

    etherwallet-master.js:88091 ReferenceError: $ is not defined
        at Object.u2f.isIosChrome_ (etherwallet-master.js:20618)
        at Object.u2f.getMessagePort (etherwallet-master.js:20595)
        at Object.u2f.getPortSingleton_ (etherwallet-master.js:20954)
        at Object.u2f.getApiVersion (etherwallet-master.js:21083)
        at Object.u2f.sign (etherwallet-master.js:21000)
        at Ledger3.exchange (etherwallet-master.js:19874)
        at LedgerEth.getAddress (etherwallet-master.js:19670)
        at ChildScope.$scope.scanLedger (etherwallet-master.js:5226)
        at fn (eval at compile (etherwallet-master.js:88942), <anonymous>:4:150)
        at callback (etherwallet-master.js:101370)

On website connect to Ledger is working, but this in this branch it is not.

**Comment by gamalielhere** [comment]
@un1t thanks for testing it! Are you serving the static files through a server?

**Comment by un1t** [comment]
No previously I just open index.html in dist folder.

Now I tried with server. I see the same errors.

**Comment by un1t** [comment]
I tried master branch and I see the same error, I guess it something with build.
Maybe there are additional steps to build it properly or do I need specific version of node.js?

**Comment by gamalielhere** [comment]
@un1t you need to run `npm install; npm run build`. Also don't use the master branch. Use mercury. I just made a push that should  fix the generation issue. But let me know if it doesn't.

**Review by kvhnuke — APPROVED** [review]

**Pull request merged**
