### PR TITLE
Show transaction QR

### PR DESCRIPTION
**Pull request by ghost**
Tested @ Chrome/OS X only

### CODE REVIEW

**Comment by ghost** [comment]
Don't pull yet. Occasionally hides the raw & signed tx strings for some reason.

**Comment by ghost** [comment]
Should be fine now. I still get the hidden textarea bug occasionally but that isn't related to these changes. Tested @ Chrome & FF on OS X.

**Comment by emprisupriatna** [comment]
Gak tahu

**Comment by kvhnuke** [comment]
I believe this is outdated, please open a new PR if possible

**Pull request closed without merging**
