### PR TITLE
Digital Bitbox support

### PR DESCRIPTION
**Pull request by douglasbakkum**
Hello. Thank you for your greatly useful wallet.

Stemming from numerous customer requests, we would like to add support for the Digital Bitbox hardware wallet (digitalbitbox.com) to MyEtherWallet. We are happy to provide a device for testing purposes. 

As a reference for anyone reading, our latest firmware `v2.2.2` is recently released and adds support for a MyEtherWallet integration ([website](https://digitalbitbox.com/firmware), [github](https://github.com/digitalbitbox/mcu/releases/tag/v2.2.2)). A copy of this PR branch is running at https://digitalbitbox.com/mew.

With respect to the referral link, for your information, details of our affiliate program can be found at https://digitalbitbox.com/policies#affiliate

### CODE REVIEW

**Comment by tayvano** [comment]
Just shot you an email. 🎉

**Comment by tayvano** [comment]
(Oh and don't worry about conflicts at the moment. We have a couple other updates so best to resolve right before we're ready to pull in. I can assist with this)

**Comment by douglasbakkum** [comment]
Thanks! We'll send test devices soon.

**Comment by tayvano** [comment]
Just got them. Will take a look tomorrow and start testing! Thank you!

**Comment by dternyak** [comment]
@douglasbakkum Please resolve conflicts :)

**Comment by dternyak** [comment]
Also, please remove changes to `chrome-extension/js/etherwallet-master.js` and `dist/js/etherwallet-master.js`

**Comment by douglasbakkum** [comment]
Will do! Cheers.

**Comment by tayvano** [comment]
@douglasbakkum I think i got it -- will you test? im on the road: https://kvhnuke.github.io/etherwallet/#send-transaction

**Comment by douglasbakkum** [comment]
@tayvano  Thanks!
Sorry - I missed this notification somehow. There is a problem connecting to the Digital Bitbox on this MEW version (our old local copy still works). I will try to fix it hopefully by end of tomorrow.
Cheers.

**Comment by Zwilla** [comment]
can you send me a BitBox for testing?

**Comment by douglasbakkum** [comment]
@tayvano I found the problem - it is on our end and will require a few extra days to fix (in firmware). The good news is that the Digital Bitbox will then *only* work with `https://www.myetherwallet.com` (and `https://digitalbitbox.com`) for Ether use cases. This will eliminate fake MEW site attacks if the Digital Bitbox is used.

@Zwilla If you would like to discuss dev work, please contact support@digitalbitbox.com. Note that we will only provide MyEtherWallet support to the official MyEtherWallet team.

**Comment by Zwilla** [comment]
@douglasbakkum does this mean that your stick will not work for users on cold places?

**Comment by douglasbakkum** [comment]
@Zwilla If you mean on an airgapped computer, then yes. Note that a hardware wallet IS a cold place (cold storage).

**Comment by douglasbakkum** [comment]
@tayvano @dternyak I updated the firmware and fixed (and tested) the problem. Sorry for the delay -- it is important to take our time and be careful when signing and releasing firmware.

The new firmware is available at [digitalbitbox.com/firmware](digitalbitbox.com/firmware)

I will make a new PR to fix some minor bugs.

Thanks!

**Pull request merged**
