### PR TITLE
[Network] Add Musicoin support

### PR DESCRIPTION
**Pull request by ghost**
Closes https://github.com/kvhnuke/etherwallet/pull/1724

+ Added musicoin support
+ Updated css for X888 & MUSIC node

### CODE REVIEW

**Comment by ghost** [comment]
Requesting review from @kvhnuke @gamalielhere @frankurcrazy @Varunram @trustfarm-dev

**Review by gamalielhere — APPROVED** [review]
Looks good to me. @kvhnuke thoughts?

**Review by Varunram — APPROVED** [review]
Looks good, thanks!

**Comment by frankurcrazy** [comment]
Looks good to me!

**Pull request merged**
