### PR TITLE
SmartBillions contract address change

### PR DESCRIPTION
**Pull request by SmartBillions**
SmartBillions contract improved after the Hackathon event.
https://www.reddit.com/r/ethereum/comments/74d3dc/smartbillions_lottery_contract_just_got_hacked/dnylbxf/

### CODE REVIEW

**Comment by vvasic** [comment]
Hello, the default PLAY has been already reserved by us see #1064. Our ICO is active and near the end. There was also an open issue #1059.

**Comment by SmartBillions** [comment]
The Play token name was reserved by SmartBillions first.
Please see https://github.com/kvhnuke/etherwallet/pull/1014
The PLAY token was reserved in requested #1014 and than it was changed by the third party. 
Now we want to change the Token address to the correct address that belongs to the SmartBillions contract.

**Comment by apetersson** [comment]
Given the recent history of SmartBillions and the proposed changes, i would urge caution towards the @kvhnuke and @tayvano concerning this pull request.

**Comment by apetersson** [comment]
see also: https://www.reddit.com/r/ethereum/comments/74d3dc/smartbillions_lottery_contract_just_got_hacked/

**Comment by SmartBillions** [comment]
SmartBillions were registered before, the smart contract was improved after the hackathon event and the address was updated. The PLAY token was registed before as a SmartBillions Token.
Please change the contract address.

**Comment by tayvano** [comment]
I don't give two fucks about who was first, who was second, who is legit, who is not. I gave up on doing diligence or even keeping track of all these tokens. In my opinion all ya'll are greedy mother fuckers, don't have the best interests of Ethereum at heart, and I'm not going to play mommy.

Ask yourself what is best for Ethereum. Obviously, 2 tokens of the same name is not best for Ethereum. Therefore, the next PR or comment on this issue should be both of you agreeing on what is what.

**Comment by SmartBillions** [comment]
SmartBillions decided to change the Token name to Smart #1111

**Comment by vvasic** [comment]
Great that we have come to a conclusion. Submitted PR #1114

**Pull request closed without merging**
