### PR TITLE
Add GoChain node

### PR DESCRIPTION
**Pull request by r-gochain**
## Description

 GoChain is a scalable, Ethereum based smart contract blockchain that is fast, secure and green.

- Homepage: https://gochain.io/
- Node: https://rpc.gochain.io/
- Explorer: https://explorer.gochain.io/
- BIP44 / Chainid 6060 ( satoshilabs/slips#284 )

## Changes

- This  PR adds GoChain node support

### CODE REVIEW

**Comment by rharipra** [comment]
👍

**Comment by AnilRaju** [comment]
You guys can do it !

**Review by gamalielhere — APPROVED** [review]

**Comment by treeder** [comment]
Thanks! Any idea when this would go live?

**Comment by Rokson33** [comment]
Great news !

**Comment by gamalielhere** [comment]
@treeder should go live when we make a new release

**Pull request merged**
