### PR TITLE
Update ht.js

### PR DESCRIPTION
**Pull request by nogo10**
First part and Help section remaining

### CODE REVIEW

**Comment by nogo10** [comment]
I have more translated material ready to add. Which file do I edit? Have additional lines been added? The translators are locals Im paying out of pocket and they are doing their best.

**Comment by nogo10** [comment]
ok it's done.. Can someone please tell me what the conflicts are exactly? I revised the whole script file according to template

**Comment by nogo10** [comment]
Since I translated the whole ht.js, there have been additional changes. Why wasn't the file updated before? The work was done. Now we must redo the whole translation line by line. Can the devs explain what procedure to follow once we commit?

**Comment by tayvano** [comment]
I cannot merge unless the merge conflicts are resolved. This pull request has never been mergable. If it is mergable, we merge it. Simple as that.

**Comment by nogo10** [comment]
If further changes are made to the script file, during a long delay, imerge conflicts will arise.

**Comment by jzu** [comment]
Ok, let me step in. While I don't really understand what caused the merge conflicts. I suggest closing this PR, and create a new one with the current, pending translation (which looks kosher enough to me) in order to start over with a clean slate. What do you think?

**Comment by nogo10** [comment]
I'm all in for getting the translation done and committed without errors. I committed 22hours ago and it still didn't show up here. Ill do as you suggest and hope for the best. Hopefully the git robot merge thingy will be helpful.

**Pull request closed without merging**
