### PR TITLE
Enable Ledger Hardware Wallet support for Akroma (AKA)

### PR DESCRIPTION
**Pull request by mkrufky**
A few minor details were left out of the Akroma PR #1976 for the Ledger.  This takes care of those - please merge.

### Ledger Support

Full 32bit Chain ID support: (merged)
https://github.com/LedgerHQ/blue-app-eth/commit/8260268b0214810872dabd154b476f5bb859aac0
https://github.com/LedgerHQ/blue-app-eth/commit/74c085ca2d032179fcf205cda1dee38c92877933

Official Ledger Akroma app PR: (merged)
https://github.com/LedgerHQ/blue-app-eth/pull/19

Akroma is on LedgerHQ official roadmap:
https://trello.com/c/TbLAr4Ik/113-akroma-support

cc: @detroitpro

### CODE REVIEW

**Comment by detroitpro** [comment]
nice catch - thanks mike

**Comment by ghost** [comment]
Looks nice, did you tested on your local environment?

**Comment by mkrufky** [comment]
Yes, tested locally using chrome

screenshot from 2018-08-04 11-31-41
screenshot from 2018-08-04 11-35-21-

**Comment by mkrufky** [comment]
Tested locally in chrome:
screenshot from 2018-08-04 11-42-53
screenshot from 2018-08-04 11-43-56

**Review by gamalielhere — APPROVED** [review]

**Pull request merged**
