### PR TITLE
Added CREDO Token to Defaults

### PR DESCRIPTION
**Pull request by dgobaud**
Website: https://bitbounce.io/

### CODE REVIEW

**Comment by stewartdennis** [comment]
I am the project lead for the Credo token. I would be happy to answer questions if needed.

**Comment by tayvano** [comment]
@macgregordennis Would love a support email address that we can pass along in case we encounter any issues that we don't know the answer to. Thanks!

**Comment by stewartdennis** [comment]
@tayvano Sure! For now, people can just contact me directly at: stewart@team.bitbounce.io

Thanks for the merge!

**Comment by kg0579** [comment]
Im waiting the ico of credo now. I decided it after reading the tweet by Tim Draper

**Pull request merged**
