### PR TITLE
Add DomainSale tab and functionality

### PR DESCRIPTION
**Pull request by mcdee**
As per discussion with Taylor, this PR provides a DomainSale tab with the ability to buy and sell ENS domains in a secondary market.

Currently restricted to Ropsten only pending successful integration in to main codebase.  A future PR will enable this on mainnet.

### CODE REVIEW

**Comment by bstashio** [comment]
Great idea, great effort!

**Comment by tayvano** [comment]
Alright let's do this. Aiming for tomorrow PM

**Comment by dternyak** [comment]
@mcdee Hey Jim,

Domain Sale is an awesome product, great work! I was prototyping on an ENS aftermarket myself, so it's great to see this product come to life!

As you may know, the MEW team is working on our react/redux/typescript based [V4 Re-write](https://github.com/myetherwallet/myetherwallet) to ensure that we have a stable foundation for the future of the product.

We're trying to release V4 as soon as we have feature-parity with V3 (and complete our audit), but we don't have Domain Sale as one of the blocking issues in our tracker.

Do you have interest / ability / bandwidth for helping to integrate Domain Sale into V4, so that we can launch V4 while continuing to support Domain Sale without linking out to the existing V3 implementation? I apologize for the miscommunication that's resulting in multiple implementations of the Domain Sale, as I wasn't aware of this on-going effort.

Looking forward to hearing from you.

**Comment by mcdee** [comment]
I have no time to tackle this at current, I'm afraid.

**Pull request merged**
