### PR TITLE
Farsi Translation added.

### PR DESCRIPTION
**Pull request by shayanb**

### CODE REVIEW

**Comment by tayvano** [comment]
Hi—can you please resubmit without the changes to chrome-extension/ or dist/ (just app/). Help us keep things clean. Thanks so much! Looks great otherwise.

**Comment by shayanb** [comment]
@tayvano Thanks for the fast response. you are great!

Sorry for the messy commits, had a long day.
Let me know if you need me to resubmit everything with less commits, maybe just one :)

**Comment by tayvano** [comment]
Long day over here as well. I just copied your fa.js and will push it manually. Take a look tomorrow AM and make sure everything looks good on the site & let me know if we can be of further assistance. 

Thanks so much for adding the translation!

**Comment by shayanb** [comment]
@tayvano I just saw the manual merge. Thank you.

**Pull request closed without merging**
