### PR TITLE
Add "Display address on TREZOR"

### PR DESCRIPTION
**Pull request by karelbilek**
Finally got around to this

https://github.com/kvhnuke/etherwallet/issues/651

The actual change is fairly small, most of the PR is the new trezorconnect script, plus the translations.

I have added the link to the balance directive, since that is where the address is.

### CODE REVIEW

**Comment by tayvano** [comment]
Kickass! Can you let me know when signing is enabled via connect? We are adding more and more support to https://www.myetherwallet.com/signmsg.html

**Comment by karelbilek** [comment]
We are now adding it :) however, there are some issues with compatibility with other wallets, we will discuss that

**Comment by tayvano** [comment]
You are amazing. Let us know if we can do anything to assist.

**Comment by karelbilek** [comment]
Here is the issue

https://github.com/ethereum/go-ethereum/issues/14794

We are using length as bitcoin varint. So our signatures are not compatible with geth signatures (which are incompatible with myetherwallet signatures).

**Comment by tayvano** [comment]
I was talking to Aaron @ MetaMask earlier regarding this. There is no real formal signing spec (that isn't inherently flawed?). 

We will do our best to match whatever standard emerges, so please do not worry about doing something differently to work for us specifically—it's far easier for us to adapt than you / geth. 😉 

Aaron and Dan at MetaMask have some opinions on the matter. I'll point them to that thread to chime in as necessary.

**Comment by tayvano** [comment]
@runn1ng For some reason when I compile for production (`gulp prep`) it throws errors. Any ideas (I'm not operating at full capacity atm, but can look again in the AM)

screen shot 2017-08-09 at 5 32 34 am

**Comment by karelbilek** [comment]
I will look at it

**Comment by karelbilek** [comment]
https://github.com/kvhnuke/etherwallet/pull/835

**Pull request merged**
