### PR TITLE
Add POWR ( PowerLedger ) to defaults

### PR DESCRIPTION
**Pull request by fnvhash**
https://powerledger.io/
https://mainsale.powerledger.io/
https://tge.powerledger.io/#cd-timeline

### CODE REVIEW

**Comment by tayvano** [comment]
please provide support email

**Comment by petabytestorage** [comment]
@tayvano  support email:  Meagan  mc@powerledger.io

**Comment by fnvhash** [comment]
@tayvano support email: Meagan mc@powerledger.io

**Comment by petabytestorage** [comment]
anything else i can help with this PR @tayvano  ?

**Pull request merged**
